# Generated by Django 4.2.11 on 2024-04-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_historicalperformance_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historical_performance', to='vendors.vendor'),
        ),
    ]
