# Generated by Django 4.2.11 on 2024-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='0f67b4df-fbb7-49cf-a780-80264cba7320', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
