# Generated by Django 4.2.11 on 2024-04-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='c3286855-afdb-4fc6-9564-0aa159ed9234', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='VendorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_deliveries_completed', models.IntegerField()),
                ('no_of_ratings_received', models.IntegerField()),
                ('no_of_acknowledgements_given', models.IntegerField()),
                ('no_of_pos_issued', models.IntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_stat', to='vendors.vendor')),
            ],
        ),
    ]
