# Generated by Django 4.2.11 on 2024-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_alter_purchaseorder_po_number_vendorstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='acknowledgment_date',
            new_name='acknowledgement_date',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='a857c5d8-88b4-4015-95d4-084a499a7471', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
