# Generated by Django 4.2.11 on 2024-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_rename_acknowledgment_date_purchaseorder_acknowledgement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='bd9d6f56-8707-4c2b-9863-e91755d7bb5e', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorstat',
            name='no_of_acknowledgements_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstat',
            name='no_of_deliveries_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstat',
            name='no_of_pos_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorstat',
            name='no_of_ratings_received',
            field=models.IntegerField(default=0),
        ),
    ]
