# Generated by Django 4.2.11 on 2024-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='d17f45ee-fddc-41c4-8324-8fa86b0892af', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
