# Generated by Django 4.2.11 on 2024-04-29 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0012_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='292fd496-5601-4d9f-aa9a-6948790e8cc3', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
