# Generated by Django 4.2.11 on 2024-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vendor_user_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='54e612a1-e9ab-4010-9a0e-4f68aedf4cb8', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
