# Generated by Django 4.2.11 on 2024-05-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default='6cacd81d-5453-48a7-bf3f-720f413cb081', editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
